### ISSUE TITLE
Invalid Package: expected grommet but found grommet-udacity

### ISSUE THREAD

**Issue by karloespiritu** [RyanCCollins/corporate-dashboard#6]
I'm getting this error when I run -- `npm run setup`:

npm ERR! Darwin 16.0.0
npm ERR! argv "/Users/karlo/.nvm/versions/node/v6.6.0/bin/node" "/Users/karlo/.nvm/versions/node/v6.6.0/bin/npm" "install"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3

npm ERR! Invalid Package: expected grommet but found grommet-udacity

**Comment by RyanCCollins** [comment]
Thanks, this is a recent change that I made to my Grommet fork.  Grommet can be installed from npm if needed: `npm install grommet --save` and then remove the reference to the other grommet, or you can change the package name to grommet-udacity with a global find and replace in the components.
